name=AutoPlex14
version=1.0.3
author=Nyjah
maintainer=Nyjah
sentence=AutoPlex14 — the most capable Arduino library for fourteen-segment displays
paragraph=AutoPlex14 is the simplest and most powerful Arduno library for fourteen-segment displays. Capable of displaying numerical data, text, bitmaps, custom fonts, and even Unicode characters, AutoPlex14 offers high flexibility; all while automatically handling multiplexing in the background.
category=Display
url=https://github.com/TechTronicsEngineering/AutoPlex14
architectures=*
